### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by 3DOeste** [ingadhoc/sale#279]
En una nueva venta, al querer agregar un producto salta el siguiente error, se acepta y se agrega el producto sin problemas.
En una nueva línea vuelve a pasar lo mismo.
Odoo 12, Ubuntu 18.04.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: <odoo.models.NewId object at 0x7fdcaf9bb9d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 989, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('sale.order.line(<odoo.models.NewId object at 0x7fdcaf9bb9d8>,).qty_delivered', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5510, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5354, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/sale.py", line 1329, in _inverse_qty_delivered
    line.qty_delivered_manual = line.qty_delivered
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 995, in __get__
    self.determine_draft_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1117, in determine_draft_value
    self._compute_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1051, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo/sale/sale_stock_ux/models/sale_order_line.py", line 190, in _compute_qty_delivered
    for line in self.filtered(lambda l: self.env['mrp.bom']._bom_find(
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4898, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4898, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/opt/odoo/sale/sale_stock_ux/models/sale_order_line.py", line 191, in <lambda>
    product=l.product_id).type == 'phantom'):
AttributeError: 'bool' object has no attribute 'type'

**Comment by nicomacr** [comment]
Gracias por el reporte del error
Arreglado en este PR #280

**Comment by 3DOeste** [comment]
Muchas Gracias! Solucionado!
